### ISSUE TITLE
Exception: unknown mysql type "text"

### ISSUE THREAD

**Issue by bossyang** [bakwc/mysql_ch_replicator#3]
- MySQL 8.0
- Python 3.9.18
- ClickHouse 24.7.2.13

```
[root@mysqlchreplicator ~]# mysql_ch_replicator --config config.yaml db_replicator --db rwp  --initial_only=True
[dbrepl rwp 2024-10-07 17:31:17,290     INFO] recreating database
[dbrepl rwp 2024-10-07 17:31:17,305     INFO] last known transaction ('binlog.000001', 639129544)
Traceback (most recent call last):
  File "/usr/local/bin/mysql_ch_replicator", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/mysql_ch_replicator/main.py", line 77, in main
    run_db_replicator(args, config)
  File "/usr/local/lib/python3.9/site-packages/mysql_ch_replicator/main.py", line 41, in run_db_replicator
    db_replicator.run()
  File "/usr/local/lib/python3.9/site-packages/mysql_ch_replicator/db_replicator.py", line 140, in run
    self.create_initial_structure()
  File "/usr/local/lib/python3.9/site-packages/mysql_ch_replicator/db_replicator.py", line 147, in create_initial_structure
    self.create_initial_structure_table(table)
  File "/usr/local/lib/python3.9/site-packages/mysql_ch_replicator/db_replicator.py", line 155, in create_initial_structure_table
    clickhouse_structure = self.converter.convert_table_structure(mysql_structure)
  File "/usr/local/lib/python3.9/site-packages/mysql_ch_replicator/converter.py", line 115, in convert_table_structure
    clickhouse_field_type = self.convert_field_type(field.field_type, field.parameters)
  File "/usr/local/lib/python3.9/site-packages/mysql_ch_replicator/converter.py", line 106, in convert_field_type
    clickhouse_type = self.convert_type(mysql_type)
  File "/usr/local/lib/python3.9/site-packages/mysql_ch_replicator/converter.py", line 100, in convert_type
    raise Exception(f'unknown mysql type "{mysql_type}"')
Exception: unknown mysql type "text"
```
> There are 7 tables created in database rwp_tmp.

**Comment by bakwc** [comment]
Fixed, to upgrade use `pip install --upgrade mysql_ch_replicator`
