### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by Stanpol** [bakwc/mysql_ch_replicator#40]
Running replicator for one of my tables result in the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/mysql_ch_replicator/binlog_replicator.py", line 448, in run
    for row in event.rows:
               ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mysql_ch_replicator/pymysqlreplication/row_event.py", line 565, in rows
    self._fetch_rows()
  File "/usr/local/lib/python3.12/site-packages/mysql_ch_replicator/pymysqlreplication/row_event.py", line 560, in _fetch_rows
    self.__rows.append(self._fetch_one_row())
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mysql_ch_replicator/pymysqlreplication/row_event.py", line 621, in _fetch_one_row
    row["values"] = self._read_column_data(self.columns_present_bitmap)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mysql_ch_replicator/pymysqlreplication/row_event.py", line 148, in _read_column_data
    values[name] = self.__read_values_name(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mysql_ch_replicator/pymysqlreplication/row_event.py", line 216, in __read_values_name
    else self.__read_string(1, column)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mysql_ch_replicator/pymysqlreplication/row_event.py", line 335, in __read_string
    string = string.decode(errors=decode_errors)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 10: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mysql_ch_replicator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mysql_ch_replicator/main.py", line 150, in main
    run_binlog_replicator(args, config)
  File "/usr/local/lib/python3.12/site-packages/mysql_ch_replicator/main.py", line 65, in run_binlog_replicator
    binlog_replicator.run()
  File "/usr/local/lib/python3.12/site-packages/mysql_ch_replicator/binlog_replicator.py", line 486, in run
    logger.error(f'unhandled error {str(e)}', exc_info=True)
                                        ^
UnboundLocalError: cannot access local variable 'e' where it is not associated with a value
```

I'm trying to debug and see what exactly causes UnicodeDecodeError.

**Comment by bakwc** [comment]
Need to figure out what's going on, it could repeats. Probably some value in some column not processed correctly..

**Comment by bakwc** [comment]
Probably need to add some prints to: `mysql_ch_replicator/pymysqlreplication/row_event.py`
Something like this:

```
            encoding = self.charset_to_encoding(column.character_set_name)
            try:
                string = string.decode(encoding, decode_errors)
            except LookupError:
                # python does not support Mysql encoding type ex)swe7 it will not decoding then Show origin string
                string = origin_string
            except UnboundLocalError:
                print(' === ', self.table, column)
```
At least we will know what table and column is this

**Comment by Stanpol** [comment]
I found the source of the exception. There is a table: 
```
CREATE TABLE `test` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2478808 DEFAULT CHARSET=latin1
```

As you can see the default charset is `latin1`.
Then there is a row `string = b'H\xe4llo'` which fails to decode to utf8.

`string = string.decode()` fails with `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 1: invalid continuation byte`
while `string = string.decode('latin1')` results in correctly decoded string: `Hällo`


So replicator could potentially: 
- parse `DEFAULT CHARSET` and use it for decoding
- library like `charset-normalizer` can be utilised to guess a charset
- a setting `decode_errors='ignore'/'replace'` can be added to the yaml config

**Comment by bakwc** [comment]
Fixed in `0.0.37`

**Comment by Stanpol** [comment]
Thanks a lot, I'll check it tomorrow. 
On the first glance, there might be problem with `swe7`, `dec8`, or `hp8` charsets of MySQL that are not natively supported in Python. In my case it won't be a problem as I only work with `latin1`, but someone in the future will come with a bug that `string.decode('swe7')` not existing. Additionally, MySQL knows the charset `koi8r`, while Python knows it as `koi8-r` or `koi8_r`. 
The full list of supported Python encodings is available [here](https://docs.python.org/3.13/library/codecs.html#standard-encodings). The full list of MySQL encodings: 
```sql
mysql> SHOW CHARACTER SET;
+----------+---------------------------------+---------------------+--------+
| Charset  | Description                     | Default collation   | Maxlen |
+----------+---------------------------------+---------------------+--------+
| armscii8 | ARMSCII-8 Armenian              | armscii8_general_ci |      1 |
| ascii    | US ASCII                        | ascii_general_ci    |      1 |
| big5     | Big5 Traditional Chinese        | big5_chinese_ci     |      2 |
| binary   | Binary pseudo charset           | binary              |      1 |
| cp1250   | Windows Central European        | cp1250_general_ci   |      1 |
| cp1251   | Windows Cyrillic                | cp1251_general_ci   |      1 |
| cp1256   | Windows Arabic                  | cp1256_general_ci   |      1 |
| cp1257   | Windows Baltic                  | cp1257_general_ci   |      1 |
| cp850    | DOS West European               | cp850_general_ci    |      1 |
| cp852    | DOS Central European            | cp852_general_ci    |      1 |
| cp866    | DOS Russian                     | cp866_general_ci    |      1 |
| cp932    | SJIS for Windows Japanese       | cp932_japanese_ci   |      2 |
| dec8     | DEC West European               | dec8_swedish_ci     |      1 |
| eucjpms  | UJIS for Windows Japanese       | eucjpms_japanese_ci |      3 |
| euckr    | EUC-KR Korean                   | euckr_korean_ci     |      2 |
| gb18030  | China National Standard GB18030 | gb18030_chinese_ci  |      4 |
| gb2312   | GB2312 Simplified Chinese       | gb2312_chinese_ci   |      2 |
| gbk      | GBK Simplified Chinese          | gbk_chinese_ci      |      2 |
| geostd8  | GEOSTD8 Georgian                | geostd8_general_ci  |      1 |
| greek    | ISO 8859-7 Greek                | greek_general_ci    |      1 |
| hebrew   | ISO 8859-8 Hebrew               | hebrew_general_ci   |      1 |
| hp8      | HP West European                | hp8_english_ci      |      1 |
| keybcs2  | DOS Kamenicky Czech-Slovak      | keybcs2_general_ci  |      1 |
| koi8r    | KOI8-R Relcom Russian           | koi8r_general_ci    |      1 |
| koi8u    | KOI8-U Ukrainian                | koi8u_general_ci    |      1 |
| latin1   | cp1252 West European            | latin1_swedish_ci   |      1 |
| latin2   | ISO 8859-2 Central European     | latin2_general_ci   |      1 |
| latin5   | ISO 8859-9 Turkish              | latin5_turkish_ci   |      1 |
| latin7   | ISO 8859-13 Baltic              | latin7_general_ci   |      1 |
| macce    | Mac Central European            | macce_general_ci    |      1 |
| macroman | Mac West European               | macroman_general_ci |      1 |
| sjis     | Shift-JIS Japanese              | sjis_japanese_ci    |      2 |
| swe7     | 7bit Swedish                    | swe7_swedish_ci     |      1 |
| tis620   | TIS620 Thai                     | tis620_thai_ci      |      1 |
| ucs2     | UCS-2 Unicode                   | ucs2_general_ci     |      2 |
| ujis     | EUC-JP Japanese                 | ujis_japanese_ci    |      3 |
| utf16    | UTF-16 Unicode                  | utf16_general_ci    |      4 |
| utf16le  | UTF-16LE Unicode                | utf16le_general_ci  |      4 |
| utf32    | UTF-32 Unicode                  | utf32_general_ci    |      4 |
| utf8mb3  | UTF-8 Unicode                   | utf8mb3_general_ci  |      3 |
| utf8mb4  | UTF-8 Unicode                   | utf8mb4_0900_ai_ci  |      4 |
+----------+---------------------------------+---------------------+--------+```

**Comment by bakwc** [comment]
Added better conversion table. For missing charsets - will add if someone request them.

**Comment by Stanpol** [comment]
No more unicode errors for me. Thank you for a quick fix, great job!
